# Generated by Django 4.2.11 on 2024-05-21 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0413_user_hedgehog_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="available_features",
        ),
    ]
